# The MacOS version 10.13 has been targeted due to the function kFSEventStreamEventFlagItemCloned that was used
# https://developer.apple.com/documentation/coreservices/1455361-fseventstreameventflags/kfseventstreameventflagitemcloned
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.13                  # [osx and x86_64]
CONDA_BUILD_SYSROOT:       # [osx and x86_64]
  - /opt/MacOSX10.13.sdk   # [osx and x86_64]
