{% set name = "watchdog" %}
{% set version = "2.1.5" %}
{% set hash = "5563b005907613430ef3d4aaac9c78600dd5704e84764cb6deda4b3d72807f09" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [py<36]
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  run_constrained:
    - __osx >=10.13
  build:
    - {{ compiler('c') }}  # [osx]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - argh >=0.24.1
    - pyyaml >=3.10

test:
  requires:
    - pip
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.observers.fsevents  # [osx]
    - watchdog.tricks
    - watchdog.utils
    - _watchdog_fsevents  # [osx]
  commands:
    - python -m pip check
    - watchmedo --help

about:
  home: http://github.com/gorakhargosh/watchdog
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Filesystem events monitoring
  doc_url: http://pythonhosted.org/watchdog
  dev_url: http://github.com/gorakhargosh/watchdog

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - ccordoba12
    - andfoy
    - tschoonj
