{% set name = "watchdog" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchdog-{{ version }}.tar.gz
  sha256: eebaacf674fa25511e8867028d281e602ee6500045b57f43b08778082f7f8b44

build:
  number: 1
  skip: True  # [py<38]
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  run_constrained:
    - __osx >=10.13
    # pytests randomly failed on osx-64
    - blas=*=openblas  # [osx and x86_64]
  build:
    - {{ compiler('c') }}  # [osx]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    # Extra require
    - pyyaml >=3.10

# https://github.com/gorakhargosh/watchdog/issues/1097 - Issue created.
# For some reason win + py313 thread initialization failed on threading.Thread.start(self)
#   emitter.start() ->
#       threading.Thread.start(self) ->
#           _start_joinable_thread(self._bootstrap, handle=self._handle, daemon=self.daemon) ->
#                 TypeError: 'handle' must be a _ThreadHandle
{% set ignore_tests = " --ignore=tests/test_emitter.py" %}  # [win and py>312]
{% set tests_to_skip = "test___init__" %}   # [win and py>312]
{% set tests_to_skip = tests_to_skip + " or test_root_deleted" %}  # [win and py>312]
{% set tests_to_skip = tests_to_skip + " or test_tricks_from_file" %}  # [win and py>312]

test:
  source_files:
    - setup.cfg
    - tests/
  requires:
    - pip
    # cannot import name 'call_runtest_hook' from '_pytest.runner'
    # https://github.com/box/flaky/issues/198#issuecomment-1989004866
    # We can update flaky to version 3.8.0 or add upper-bound for the pytest to save compatibility.
    - pytest <7
    - pytest-timeout
    - pytest-cov
    - flaky
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.observers.fsevents  # [osx]
    - watchdog.tricks
    - watchdog.utils
    - _watchdog_fsevents  # [osx]
  commands:
    - pip check
    - watchmedo --help
    - pytest -v tests  # [not (win and py>312)]
    - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" tests  # [win and py>312]

about:
  home: https://github.com/gorakhargosh/watchdog
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Filesystem events monitoring
  description: |
    Watchdog: Python API library and shell utilities to monitor file system events.
  doc_url: https://pythonhosted.org/watchdog
  dev_url: https://github.com/gorakhargosh/watchdog

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - ccordoba12
    - andfoy
    - tschoonj
