{% set name = "watchdog" %}
{% set version = "0.10.2" %}
{% set hash_type = "sha256" %}
{% set hash = "c560efb643faed5ef28784b2245cf8874f939569717a4a12826a173ac644456b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - argh >=0.24.1
    - pathtools >=0.1.1
    - pyyaml >=3.10

test:
  requires:
    - pip
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.observers.fsevents  # [osx]
    - watchdog.tricks
    - watchdog.utils
    - _watchdog_fsevents  # [osx]
  commands:
    - python -m pip check
    - watchmedo --help

about:
  home: http://github.com/gorakhargosh/watchdog
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Filesystem events monitoring'
  doc_url: http://pythonhosted.org/watchdog

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - ccordoba12
    - andfoy
