{% set name = "watchdog" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchdog-{{ version }}.tar.gz
  sha256: eebaacf674fa25511e8867028d281e602ee6500045b57f43b08778082f7f8b44

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  run_constrained:
    - __osx >=10.13
  build:
    - {{ compiler('c') }}  # [osx]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    # Extra require
    - pyyaml >=3.10

test:
  requires:
    - pip
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.observers.fsevents  # [osx]
    - watchdog.tricks
    - watchdog.utils
    - _watchdog_fsevents  # [osx]
  commands:
    - python -m pip check
    - watchmedo --help

about:
  home: https://github.com/gorakhargosh/watchdog
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Filesystem events monitoring
  doc_url: https://pythonhosted.org/watchdog
  dev_url: http://github.com/gorakhargosh/watchdog

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - ccordoba12
    - andfoy
    - tschoonj
