{% set name = "watchdog" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchdog-{{ version }}.tar.gz
  sha256: b4dfbb6c49221be4535623ea4474a4d6ee0a9cef4a80b20c28db4d858b64e270

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
  run_constrained:
    - __osx >=10.13
    - pyyaml >=3.10

{% set tests_to_skip = "test_renaming_top_level_directory" %}

test:
  source_files:
    - pyproject.toml
    - tests/
  requires:
    - pip
    - pytest <8
    - pytest-timeout
    - pytest-cov
    - flaky
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.observers.fsevents  # [osx]
    - watchdog.tricks
    - watchdog.utils
    - _watchdog_fsevents  # [osx]
  commands:
    - pip check
    - watchmedo --help
    - pytest tests -vv  # [not win]
    - pytest -k "not ({{ tests_to_skip }})" tests -vv  # [win]

about:
  home: https://github.com/gorakhargosh/watchdog
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Filesystem events monitoring
  description: |
    Watchdog: Python API library and shell utilities to monitor file system events.
  doc_url: https://pythonhosted.org/watchdog
  dev_url: https://github.com/gorakhargosh/watchdog

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - ccordoba12
    - andfoy
    - tschoonj
