{% set name = "watchdog" %}
{% set version = "0.10.0" %}
{% set hash_type = "sha256" %}
{% set hash = "8e800496cdfb921cfdc62b58a11966d0d2203a35dc005b4b5b8e1ab3097b2eb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1
  entry_points:
    - watchmedo = watchdog.watchmedo:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - argh >=0.24.1
    - pathtools >=0.1.1
    - pyyaml >=3.10
    - pyobjc-framework-cocoa >=4.2.2  # [osx]
    - pyobjc-framework-fsevents >=4.2.2  # [osx]

test:
  requires:
    - pip
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.observers.fsevents  # [osx]
    - watchdog.tricks
    - watchdog.utils
  commands:
    - python -m pip check
    - watchmedo --help

about:
  home: http://github.com/gorakhargosh/watchdog
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Filesystem events monitoring'
  doc_url: http://pythonhosted.org/watchdog

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - ccordoba12
    - andfoy
