travis:
  secure:
    BINSTAR_TOKEN: VM4R9Y1d37QUkcXYnbNWveC6vQ0DNiV+Z18TxmQo7UKxFm7inFA9jR2e1EMJcFiCgoUYGi5ZWKoXAZsxV6rvnNNNlgiBF16voKjQi1KsBg9pjutEGxnAwsHH9wzepA+jPh1suKhccKEBsbXmQlLDqZwdG609lQaQhjQyjo/Ek+rZIfeMjk2Nl1izk0ApXeyrixSqTuTcyAq76ieKJXBsv5y1GOocghLipWDoDNP9062zMRWy3W8eR72kQXnGREw1hTeYSzqS7X76FhYUVhX2NDSGXK36kpBLQ4Jeq80B8ZMpu1Mnu9LsDwSMxyjEsEKoIxWewvy+1yKQg7NKRtrBycYM9RgpbFOoJDwckE1+gkKjzeqxWlb5R4Ab9zxbMgurF4I4k2OdnebNSFpHvh52AuSGS2wDl5vWdflKmMW0/KfGUqQ0H43XiWUXse/QwpI70xrUOVoDLFfuatp14rFEjazbFN+7N3FoAmzgltumzqAIKYgMCZT7pWw4jo5/1iYiRq8yHbHVEA9i0z1st4FsNn+w+bwJqyOe1k7b9kM44MenPENkssh0Ps4jSQ/HfX5WHTY811+7Bh4STYOlSwfxVgW6SLtM5/PAEuDxtcoQbPaMQagnuYp11lfWB/9XqBukWluUwj8c7osYZGnsJE2FJakKwuzQ233a3z2yXc5l1/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
